name: "AI_GENETIC"
description: "Using genetic algorithm to get a voltage configuration for RNPU hysteresis effect."
device_measured: "RNPU"
min_value: -1.25
max_value: 1.25
data_density: 21
voltage_range: [-1.5, 1.5]
current_range: [-300e-9, 300e-9]
amplification: 1
wavetype: 'SWEEP'

RNPU:
  input_electrodes: 7
  control_electrodes: [0, 1, 2, 4, 5, 6, 7]
  output_electrodes: "IV"
  sweep_all: False

GA:
  num_generations: 20
  num_parents_mating: 5
  sol_per_pop: 10
  gene_space: {"low": -0.9, "high": 0.9}
  mutation_type: "random"
  mutation_percent_genes: 10
  mutation_num_genes: 1

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 10000.0
  update_frequency: 10000.0
  ramp_points: 1000
  samples_per_measurement: 5
  readout_channels: [0, 1, 2, 4, 5, 6, 7] #0-7
  control_voltages:
    0: 0
    1: 0
    2: 0
    4: 0
    5: 0
    6: 0
    7: 0

K2400:
  device_id: 'GPIB16::15::INSTR'
  timeout: 50000
  drive_mode: 'VOLTAGE_DRIVEN'
  tolerance_voltage: 0.01
  tolerance_current: 10e-9
  pause_between_set: 0.02