name: "IV_DYNAMIC_HYSTERESIS_TEST"
description: "IV Curve for RNPU to check math concept functionality."
device_measured: "RNPU"
min_value: -1.5
max_value: 1.5
data_density: 61
voltage_range: [-2.0, 2.0]
current_range: [-300e-9, 300e-9]
amplification: 1
waveform: 'REZA'
input_pad: 7
output_pad: "IV"
cv1_pad: 2
cv2_pad: 4
resistance: 0

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 10000.0
  update_frequency: 5000.0
  ramp_points: 3000
  samples_per_measurement: 5
  readout_channels: [7, 2, 4] #0-7
  control_voltages:
    7: 0
    2: -0.2
    4: 1.0

K2400:
  device_id: 'GPIB16::15::INSTR'
  timeout: 50000
  drive_mode: 'VOLTAGE_DRIVEN'
  tolerance_voltage: 0.01
  tolerance_current: 10e-9
  pause_between_set: 0.02