name: "IV_RNPU_3T"
description: "Standard IV Measurement. 300mV Control Voltage"
min_value: -1.5
max_value: 1.5
data_density: 120
voltage_range: [-2.0, 2.0]
current_range: [-500e-9, 500e-9]
amplification: 1
waveform: 'REZA'

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 4000.0
  update_frequency: 1000.0
  ramp_points: 3000
  samples_per_measurement: 5
  readout_channels: [2, 3] # 0-7
  control_voltages:
    3: -0.300

smu:
  device_id: 'GPIB0::15::INSTR'
  timeout: 50000
  drive_mode: 'VOLTAGE_DRIVEN'
  tolerance_voltage: 0.01
  tolerance_current: 10e-9
  pause_between_set: 0.02