name: "IV_TEST_VOLT_3T"
description: "IV Measurement but with Current measurement using the SMU and an opposing voltmeter. This data is saved as current_ei.csv. 0mV Control Voltage. Physically onnected pads: 2, I, III"
min_value: -1.5
max_value: 1.5
data_density: 60
voltage_range: [-2.0, 2.0]
current_range: [-500e-9, 500e-9]
amplification: 1
waveform: 'REZA'

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 4000.0
  update_frequency: 1000.0
  ramp_points: 3000
  samples_per_measurement: 5
  readout_channels: [2] # 0-7
  control_voltages:
    2: 0

smu:
  device_id: 'GPIB15::15::INSTR'
  timeout: 50000
  drive_mode: 'VOLTAGE_DRIVEN'
  tolerance_voltage: 0.01
  tolerance_current: 10e-9
  pause_between_set: 0.02

K195:
  device_id: '"GPIB1::11::INSTR"'
  measurement_mode: 'current'
  range: 2
  timeout: 50000