name: "TEST_VOLTMETER"
description: "Tests to see if communication to the voltmeter (K195) works."
min_value: -2.0
max_value: 2.0
data_density: 25
voltage_range: [-2.0, 2.0]
current_range: [-500e-9, 500e-9]
amplification: 1
waveform: 'REZA'

nidaq:
  activation_module_id: 'cDAQ1Mod1'
  readout_module_id: 'cDAQ1Mod2'
  sample_frequency: 4000.0
  update_frequency: 1000.0
  ramp_points: 3000
  samples_per_measurement: 5
  readout_channels: [0]
  control_voltages:
    7: 0
    6: 0
    5: 0
    4: 0

K195:
  device_id: 11
  measurement_mode: 'voltage'
  range: 10
  timeout: 50000